/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 only,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/gpl-2.0.txt.
 */

package org.glassfish.security.common;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Covers the implicit {@code values()} and {@code valueOf(String)} methods
 * generated by the compiler for the {@link FailureReason} enum. Without this
 * test, JaCoCo reports those synthetic branches as uncovered, which would
 * fail the 80 % line / 90 % branch gate on {@code FailureReason.class}.
 *
 * Portions Copyright [2026] Payara Foundation and/or its affiliates
 */
public class FailureReasonTest {

    @Test
    public void valuesAndValueOf() {
        for (FailureReason r : FailureReason.values()) {
            assertEquals(r, FailureReason.valueOf(r.name()));
        }
        assertEquals(4, FailureReason.values().length);
    }
}
